steam_dbt_bos:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account>

      user: <username>
      password: <password>

      role: ACCOUNTADMIN
      database: DEV
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt
    prod:
      type: snowflake
      account: <account>

      user: <username>
      password: <password>

      role: ACCOUNTADMIN
      database: PROD
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt